[WIP] Amended RegistrationPage to have User and Password fields Also added Views/Controls/ImageEntry.cs
WIP because of this error given by the Previewer for RegistrationPage.xaml:

Xamarin.Forms.Xaml.XamlParseException: Position 22:18. Type local:ImageEntry not found in xmlns clr-namespace:AwsDynamoDbTest.Core.Views;assembly=AwsDynamoDbTest.Core
  at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x0024b] in D:\agent_work\1\s\Xamarin.Forms.Xaml\CreateValuesVisitor.cs:92
  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x000ab] in D:\agent_work\1\s\Xamarin.Forms.Xaml\XamlNode.cs:149
  at Xamarin.Forms.Xaml.RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00078] in D:\agent_work\1\s\Xamarin.Forms.Xaml\XamlNode.cs:203
  at Xamarin.Forms.Xaml.XamlLoader.Visit (Xamarin.Forms.Xaml.RootNode rootnode, Xamarin.Forms.Xaml.HydrationContext visitorContext) [0x00054] in D:\agent_work\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:138
  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml) [0x0004b] in D:\agent_work\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:89
  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.Type callingType) [0x0002f] in D:\agent_work\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:68
  at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.Type callingType) [0x00000] in D:\agent_work\1\s\Xamarin.Forms.Xaml\ViewExtensions.cs:36
  at AwsDynamoDbTest.Core.Views.TabsPage.InitializeComponent () [0x00001] in /Users/fritzlim/Documents/Projects/Xamarin/AWS/AwsDynamoDbTest/AwsDynamoDbTest.Core/obj/Debug/netstandard2.0/AwsDynamoDbTest.Core.Views.TabsPage.xaml.g.cs:20
  at AwsDynamoDbTest.Core.Views.TabsPage..ctor () [0x00008] in /Users/fritzlim/Documents/Projects/Xamarin/AWS/AwsDynamoDbTest/AwsDynamoDbTest.Core/Views/TabsPage.xaml.cs:12
  at AwsDynamoDbTest.Core.App..ctor () [0x0000f] in /Users/fritzlim/Documents/Projects/Xamarin/AWS/AwsDynamoDbTest/AwsDynamoDbTest.Core/App.xaml.cs:11
  at AwsDynamoDbTest.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x0004b] in /Users/fritzlim/Documents/Projects/Xamarin/AWS/AwsDynamoDbTest/iOS/AppDelegate.cs:40
  at at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/UIKit/UIApplication.cs:63
  at AwsDynamoDbTest.iOS.Application.Main (System.String[] args) [0x00001] in /Users/fritzlim/Documents/Projects/Xamarin/AWS/AwsDynamoDbTest/iOS/Main.cs:17